// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI6HqF8xziQha-Mz3VZNIjwTNtpG0E7Qc',
    appId: '1:37680523976:web:d1e76deda59c72962553fd',
    messagingSenderId: '37680523976',
    projectId: 'leebanstudio',
    authDomain: 'leebanstudio.firebaseapp.com',
    storageBucket: 'leebanstudio.appspot.com',
    measurementId: 'G-1DM8NT87MF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuGx7nJjf3tXtSGgvXJJl0vSy31sgTEHs',
    appId: '1:37680523976:android:0347edb59d4b84a12553fd',
    messagingSenderId: '37680523976',
    projectId: 'leebanstudio',
    storageBucket: 'leebanstudio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLyWsU7rX95FQIMu8bDNn2M_2RE9hAm7k',
    appId: '1:37680523976:ios:b31aa44adfa8dd792553fd',
    messagingSenderId: '37680523976',
    projectId: 'leebanstudio',
    storageBucket: 'leebanstudio.appspot.com',
    iosClientId: '37680523976-kcu8d1ptpsv01du02712u4gpk55lgoef.apps.googleusercontent.com',
    iosBundleId: 'com.example.suhang',
  );
}
